name: Regen Mint Automation

on:
  # schedule:
  #   - cron: '0 4 * * *'  # 04:00 UTC every day (disabled for now)
  workflow_dispatch:      # allows manual trigger from GitHub UI

jobs:
  regen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run regenAllEligible()
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          INFURA_URL: ${{ secrets.INFURA_URL }}
        run: node scripts/triggerRegen.js
